
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20) DEFAULT 'NONE', -- NONE, PENDING, APPROVED, REJECTED
ADD COLUMN IF NOT EXISTS kyc_document_path VARCHAR(255);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS kyc_notes TEXT;
